spring.application.name=orders-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=orders_user
spring.datasource.password=1234

spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.jpa.hibernate.ddl-auto=validate

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.mvc.problemdetails.enabled=true

#The other microservices URL
payment-service.base-url=http://localhost:8081