spring.application.name=payment-service


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=orders_user
spring.datasource.password=1234

spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.jpa.hibernate.ddl-auto=validate

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.mvc.problemdetails.enabled=true